### ISSUE TITLE
RCON command not working on Papermc

### ISSUE THREAD

**Issue by Rombond** [dirien/minecraft-prometheus-exporter#228]
### What happened?

When i start minecraft-exporter, it crashes after a few second

Here the error : 
>juin 24 21:19:34 Nathan systemd[1]: Started node_exporter.
juin 24 21:19:34 Nathan minecraft-exporter[497584]: _  _ _ _  _ ____ ____ ____ ____ ____ ___    ____ _  _ ___  ____ ____ ___ ____ ____
juin 24 21:19:34 Nathan minecraft-exporter[497584]: |\/| | |\ | |___ |    |__/ |__| |___  |  __ |___  \/  |__] |  | |__/  |  |___ |__/
juin 24 21:19:34 Nathan minecraft-exporter[497584]: |  | | | \| |___ |___ |  \ |  | |     |     |___ _/\_ |    |__| |  \  |  |___ |  \
juin 24 21:19:34 Nathan minecraft-exporter[497584]: ts=2022-06-24T19:19:34.357Z caller=main.go:42 level=info msg="Starting minecraft_exporter" version="(version=0.13.0, branch=HEAD, revision=56f4e1d8b26cf029937e5ee9d9638c1d1263721e)"
juin 24 21:19:34 Nathan minecraft-exporter[497584]: ts=2022-06-24T19:19:34.357Z caller=main.go:43 level=info msg="Build context" build="(go=go1.18, user=goreleaser, date=2022-04-07T19:17:58Z)"
juin 24 21:19:34 Nathan minecraft-exporter[497584]: ts=2022-06-24T19:19:34.367Z caller=main.go:52 level=info msg="Disabling collection of exporter metrics (like go_*)" value=false
juin 24 21:19:34 Nathan minecraft-exporter[497584]: ts=2022-06-24T19:19:34.367Z caller=main.go:77 level=info msg="Listening signals..."
juin 24 21:19:34 Nathan minecraft-exporter[497584]: ts=2022-06-24T19:19:34.368Z caller=main.go:68 level=info msg="Listening on address" address=:9150
juin 24 21:19:34 Nathan minecraft-exporter[497584]: ts=2022-06-24T19:19:34.368Z caller=tls_config.go:195 level=info msg="TLS is disabled." http2=false
juin 24 21:19:46 Nathan minecraft-exporter[497584]: panic: runtime error: index out of range [1] with length 0
juin 24 21:19:46 Nathan minecraft-exporter[497584]: goroutine 37 [running]:
juin 24 21:19:46 Nathan minecraft-exporter[497584]: github.com/minecraft-exporter/pkg/exporter.(*Exporter).getPlayerList(0xc0002b4000, 0x1?)
juin 24 21:19:46 Nathan minecraft-exporter[497584]:         /home/runner/work/minecraft-prometheus-exporter/minecraft-prometheus-exporter/pkg/exporter/exporter.go:724 +0x1de
juin 24 21:19:46 Nathan minecraft-exporter[497584]: github.com/minecraft-exporter/pkg/exporter.(*Exporter).Collect(0xc0002b4000, 0xc000070f60?)
juin 24 21:19:46 Nathan minecraft-exporter[497584]:         /home/runner/work/minecraft-prometheus-exporter/minecraft-prometheus-exporter/pkg/exporter/exporter.go:847 +0x3b
juin 24 21:19:46 Nathan minecraft-exporter[497584]: github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
juin 24 21:19:46 Nathan minecraft-exporter[497584]:         /home/runner/go/pkg/mod/github.com/prometheus/client_golang@v1.12.1/prometheus/registry.go:446 +0xfb
juin 24 21:19:46 Nathan minecraft-exporter[497584]: created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
juin 24 21:19:46 Nathan minecraft-exporter[497584]:         /home/runner/go/pkg/mod/github.com/prometheus/client_golang@v1.12.1/prometheus/registry.go:457 +0x4c5
juin 24 21:19:46 Nathan systemd[1]: minecraft_exporter.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
juin 24 21:19:46 Nathan systemd[1]: minecraft_exporter.service: Failed with result 'exit-code'.

Here the log from the mc server : 
>[21:19:34 INFO]: Thread RCON Client /127.0.0.1 started
[21:19:46 INFO]: Rcon issued server command: /list
[21:19:46 INFO]: Thread RCON Client /127.0.0.1 shutting down
/list
[21:20:25 INFO]: Unknown command. Type "/help" for help.
list
[21:20:26 INFO]: CONSOLE issued server command: /list
[21:20:26 INFO]: Il y a 0 joueurs en ligne sur 20 au total.

As you can see, the RCON command sent were '/list' but i think it should be 'list' because add with the '/' the server doesn't answer

### How can we reproduce this?

Try to run minecraft-exporter on a papermc (i'm on linux)

### minecraft-exporter version

```bash
minecraft-exporter_0.13.0.linux-amd64
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dirien** [comment]
Hi @Rombond,

I tested the scenario on my side and I can't reproduce this!

the exporter is not sending any '/' for the rcon commands.

![image](https://user-images.githubusercontent.com/38325136/176117456-5d4eebd5-a758-4ad2-81e8-58842b671af5.png)


Can you check the parameter you set for the exporter? Would neet some informations to find out why you seeing the `panic: runtime error: index out of range [1] with length 0` error

Thanks

**Comment by Rombond** [comment]
Hi @dirien 

The only parameter i put to it, is the config.yaml.
Inside i have put this : 

> world-path: "/home/lumination/Documents/ServeurMinecraft/Vanilla 1.18.2/world/"
rcon-password: "******"
mod-server-stats: "papermc"

When i tested, nobody were connected on the server, i will try later with someone on connected

**Comment by dirien** [comment]
hi @Rombond,

is it vanilla or papermc? I see in your logs ->  `Vanilla 1.18.2`

**Comment by dirien** [comment]
Hi @Rombond,

debuged with PaperMC 1.18.2 version too:
![image](https://user-images.githubusercontent.com/38325136/176268635-b91ecc8e-99c6-4a67-9ec7-a8323e49826c.png)
Can't see an exception like in your stacktrace.

Now i am very interested to find the root cause.

**Comment by Rombond** [comment]
Hi @dirien 

I'm on paper 1.18.2
And i think the bug is from the line 724 :
`playersraw := e.playerOnlineRegexp.FindStringSubmatch(*resp)[1]`
You try to access to index 1 but in the error message it says that length is 0
> juin 24 21:19:46 Nathan minecraft-exporter[497584]: panic: runtime error: index out of range [1] with length 0

I'm trying to run your exporter on debug, but i never done some go before, need some time to check this

**Comment by dirien** [comment]
@Rombond, Ohhh welp I got it! You are using French! My Regex is checking on the English text! 

So let me find a better, less brittle way to handle this!

Thanks for the issue by the way! 👍

**Comment by dirien** [comment]
Hi @Rombond,

can you try the version 0.14.0 and let me know?

Just one side note, if you using the Essentials mod and changed the added groups to the /list command you may see not all the players online. I check in the return string for the first `:`.  

Just give me feedback, looking forward.

**Comment by Rombond** [comment]
Yeah it's running right now but i got a new error so i opened a new issue ;)
Thanks for your speed !
