### ISSUE TITLE
Crash when tps are not green

### ISSUE THREAD

**Issue by Rombond** [dirien/minecraft-prometheus-exporter#235]
### What happened?

Everything works well except when tps are going down, they change color then the regex is no more correct so it crashes.

> juin 30 16:21:38 Nathan minecraft-exporter[44515]: panic: runtime error: index out of range [1] with length 0
juin 30 16:21:38 Nathan minecraft-exporter[44515]: goroutine 1187 [running]:
juin 30 16:21:38 Nathan minecraft-exporter[44515]: github.com/minecraft-exporter/pkg/exporter.(*Exporter).getServerStats(0xc0002c2480, 0x1?)
juin 30 16:21:38 Nathan minecraft-exporter[44515]:         /home/runner/work/minecraft-prometheus-exporter/minecraft-prometheus-exporter/pkg/exporter/exporter.go:799 +0x44f
juin 30 16:21:38 Nathan minecraft-exporter[44515]: github.com/minecraft-exporter/pkg/exporter.(*Exporter).Collect(0xc0002c2480, 0xc001926f60?)
juin 30 16:21:38 Nathan minecraft-exporter[44515]:         /home/runner/work/minecraft-prometheus-exporter/minecraft-prometheus-exporter/pkg/exporter/exporter.go:870 +0x2c5
juin 30 16:21:38 Nathan minecraft-exporter[44515]: github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
juin 30 16:21:38 Nathan minecraft-exporter[44515]:         /home/runner/go/pkg/mod/github.com/prometheus/client_golang@v1.12.2/prometheus/registry.go:446 +0xfb
juin 30 16:21:38 Nathan minecraft-exporter[44515]: created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
juin 30 16:21:38 Nathan minecraft-exporter[44515]:         /home/runner/go/pkg/mod/github.com/prometheus/client_golang@v1.12.2/prometheus/registry.go:538 +0xb0b
juin 30 16:21:38 Nathan systemd[1]: minecraft_exporter.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
juin 30 16:21:38 Nathan systemd[1]: minecraft_exporter.service: Failed with result 'exit-code'.

### How can we reproduce this?

make your minecraft server lag
i make it lag with minecarts all in stuck in one block, with this command in a command_block `summon minecraft:minecart ~ ~-2 ~`

### minecraft-exporter version

```bash
0.14.0
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dirien** [comment]
Hi @Rombond,

thanks for reporting this one! I made the regex more stable now and released it with version `0.14.1`

looking forward for your feedback!

**Comment by Rombond** [comment]
Hi @dirien 

Works well on 0.14.1 good job ! 👍
