### ISSUE TITLE
Play Time in Ticks not exporting for large values

### ISSUE THREAD

**Issue by TMUniversal** [dirien/minecraft-prometheus-exporter#246]
### What happened?

The metric `minecraft_play_time_ticks_total` shows value `0` for higher play times.

Some real values from my server *(names redacted)*, taken directly from `/metrics` via `curl`:
```
minecraft_play_time_ticks_total{player="A"} 0				// <-- should be 15522237 ~215 hours (9 days)
minecraft_play_time_ticks_total{player="B"} 354516			// just under 5 hours
minecraft_play_time_ticks_total{player="C"} 5.203009e+06	// just over 3 days
```

#### Server Details
* Minecraft Version:  `git-Purpur-1623 (MC: 1.18.2)` (see https://purpurmc.org/)
* `/plugins`: Plugins (11): AsyncWorldEdit, CoreProtect, Essentials, EssentialsChat, EssentialsProtect, Harbor, LuckPerms, ServerRestorer, TAB, Vault, WorldEdit
* `Essentials` is [EssentialsX](https://essentialsx.net/), which messes with some of the server commands (like `/list`)

#### How to reproduce issue
* Play on a server from which you are exporting metrics for ~200 hours
* `minecraft_play_time_ticks_total` should at some point jump from whatever play time you do have to `0`

### minecraft-exporter version

```bash
minecraft_exporter, version 0.14.1 (branch: HEAD, revision: 210cc07ab55f47895f38060136d6f53942ace49a)
  build user:       goreleaser
  build date:       2022-06-30T18:29:25Z
  go version:       go1.18.3
  platform:         linux/amd64
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Does not appear related to #79 (similar issue), since some play times do export correctly.

**Comment by TMUniversal** [comment]
True Play Time of `A`: `15522237` ticks

**Comment by dirien** [comment]
Hi @TMUniversal,

thanks for the issue!

Looks like, it got renamed starting from 1.17!

![image](https://user-images.githubusercontent.com/38325136/179465655-e47f0301-9c79-4e5f-8d4b-23de3cc55a00.png)

Let me think about a good way, to make the exporter work also for < 1.17.

**Comment by dirien** [comment]
Hi @TMUniversal,

created a new release with the right custom stat name.

Please try 0.15.0 and would be cool to give some feedback if everything works fine.

**Comment by TMUniversal** [comment]
Working fine now. Thanks for your quick work! 👍 

Side Note: players that have not logged in since I've migrated the server from 1.16 have been updated by minecraft,
meaning that they also show the proper play time.

**Comment by dirien** [comment]
Ok sounds great! Thanks for the feedback @TMUniversal!
