### ISSUE TITLE
Documentation Inconsistency

### ISSUE THREAD

**Issue by TMUniversal** [dirien/minecraft-prometheus-exporter#249]
### Bug Report Template

In Section `minecraft-exporter version`, the output of `minecraft-exporter version` is requested, which results in

```
minecraft-exporter: error: unexpected version, try --help
```

while `--version` yields the desired information.

(sorry for nit-picking...)

### Mod Server Stats Flag

Possible typo in https://github.com/dirien/minecraft-prometheus-exporter/blob/main/README.md?plain=1#L175 (Config Section)

Differs from https://github.com/dirien/minecraft-prometheus-exporter/blob/main/README.md?plain=1#L153 (Usage Section)

Using the flag `--mod-server-stats` results in failure to start the process.

```
Jul 18 15:43:14 machine systemd[1]: Started Minecraft Exporter.
Jul 18 15:43:14 machine minecraft-exporter[18469]: minecraft-exporter: error: unknown long flag '--mod-server-stats', try --help
Jul 18 15:43:14 machine systemd[1]: minecraft_exporter.service: Main process exited, code=exited, status=1/FAILURE
Jul 18 15:43:14 machine systemd[1]: minecraft_exporter.service: Failed with result 'exit-code'.
```

Works with `--mc.mod-server-stats`

### How can we reproduce this?

* Start `minecraft-exporter` with arg `--mod-server-stats`
* See process status

```service
[Unit]
Description=Minecraft Exporter
Wants=network-online.target
After=network-online.target
[Service]
User=prometheus
Group=prometheus
Type=simple
ExecStart=/usr/local/bin/minecraft-exporter \
  --mc.rcon-address="<host:port>" \
  --mc.rcon-password=<rcon password> \
  --mc.world=/path/to/world \
  --mod-server-stats=papermc
[Install]
WantedBy=multi-user.target
```

* Works with `--mc.mod-server-stats`

### minecraft-exporter version

```bash
minecraft_exporter, version 0.15.0 (branch: HEAD, revision: 39f5c9af230852b7de3ed8853af3ad2cb92b9e6b)
  build user:       goreleaser
  build date:       2022-07-18T09:46:44Z
  go version:       go1.18.3
  platform:         linux/amd64
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Obviously this is not a bug report, but there is (as of yet) no template for editorial changes.

**Comment by dirien** [comment]
Ok, there is a spelling error :) It must be `--mc.mod-server-stats`

I will update the docs!

**Comment by TMUniversal** [comment]
Thanks ^^, please also have a look at the issue with the bug report template (`--version` ouput)

**Comment by dirien** [comment]
> Also (sorry for posting this here, as it might be an issue), using the `--mc.mod-server-stast=papermc` on a Purpur (fork of Paper) Server does not yield `tps` stats (not `0`, they don't export)

Ah okay looks liek purpur renders the tps different then paper!

```bash
[17:02:56 INFO]: Unknown command. Type "/help" for help.
[17:02:56 INFO]: [⚡] TPS from last 5s, 10s, 1m, 5m, 15m:
[17:02:56 INFO]: [⚡]  20.0, 20.0, 20.0, 20.0, 20.0
[17:02:56 INFO]: [⚡]
[17:02:56 INFO]: [⚡] Tick durations (min/med/95%ile/max ms) from last 10s, 1m:
[17:02:56 INFO]: [⚡]  50.6/50.7/76.6/76.6;  50.6/50.7/76.6/76.6
[17:02:56 INFO]: [⚡]
[17:02:56 INFO]: [⚡] CPU usage from last 10s, 1m, 15m:
[17:02:56 INFO]: [⚡]  0%, 0%, 0%  (system)
[17:02:56 INFO]: [⚡]  0%, 0%, 0%  (process)
````

@TMUniversal, would you mind to create a new issue for this? along the line: Support for PurpurMC?

**Comment by TMUniversal** [comment]
https://github.com/dirien/minecraft-prometheus-exporter/blob/main/charts/minecraft-exporter/README.md?plain=1#L44 says `minecraft-exporte` (missing `r`) in the namespace

**Comment by dirien** [comment]
Hi @TMUniversal,

fixed the points. Thanks for taking the time to find the inconsistency.
