### ISSUE TITLE
Support for PurpurMC

### ISSUE THREAD

**Issue by TMUniversal** [dirien/minecraft-prometheus-exporter#250]
### Is your feature request related to a problem? Please describe.

Support PaperMC stats for the [Purpur](https://purpurmc.org/) fork.

The additional information from PaperMC is available in Purpur as well,
but is not exported by `minecraft-exporter`

PaperMC stats (according to https://github.com/dirien/minecraft-prometheus-exporter#papermc)
```
# HELP minecraft_tps_total_bucket The number of ticks per second in PaperMC
# TYPE minecraft_tps_total_bucket histogram
minecraft_tps_total_bucket_bucket{le="1"} 20
minecraft_tps_total_bucket_bucket{le="5"} 20
minecraft_tps_total_bucket_bucket{le="15"} 20
minecraft_tps_total_bucket_bucket{le="+Inf"} 3
minecraft_tps_total_bucket_sum 60
minecraft_tps_total_bucket_count 3
```

### Describe the solution you'd like

```
# HELP minecraft_tps_total_bucket The number of ticks per second in PaperMC
# TYPE minecraft_tps_total_bucket histogram
minecraft_tps_total_bucket_bucket{le="1"} 20
minecraft_tps_total_bucket_bucket{le="5"} 20
minecraft_tps_total_bucket_bucket{le="15"} 20
minecraft_tps_total_bucket_bucket{le="+Inf"} 3
minecraft_tps_total_bucket_sum 60
minecraft_tps_total_bucket_count 3
```

- [ ] stats should also be exported when using purpur
- [ ] preferrably selected via `--mc.mod-server-stats=purpur` command line argument
- [x] <s>export cpu usage as well? as it seems to be measured by purpur as well (see reference below)</s>

### Describe alternatives you've considered

- not having TPS information would be inconvenient
- switching to paper would be a problem as well, as I depend on the more advanced configuration options of [purpur](https://purpurmc.org/)

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Reference: https://github.com/dirien/minecraft-prometheus-exporter/issues/249#issuecomment-1187614611

**Comment by TMUniversal** [comment]
Console output from `/tps` (is coloured in console):

```
> tps
[17:16:22 INFO]: TPS from last 5s, 1m, 5m, 15m: 20.0, 20.0, 20.0, 20.0
```

I don't know how I can check this with `RCON`  manually.

**Comment by dirien** [comment]
Hi @TMUniversal,

you are right, somehow you can't get the `tps` output via RCON.

I checked it with the library I am using and created a issue there

(https://github.com/Tnze/go-mc/issues/208)

**Comment by dirien** [comment]
By the way, I added Purpur support to my side project `minectl 🗺`

Thanks for bringing this to my attention! 

https://github.com/dirien/minectl/pull/583

**Comment by dirien** [comment]
Hi @TMUniversal,

sorry it took so much time to answer. But this one needed some time to dig through.

Looks like the `tps` command is created my [spark](https://spark.lucko.me/), which is a:

>A performance profiler for Minecraft clients, servers, and proxies.

And it looks like that spark commands are as async accoording to this PR in the spark repo ->https://github.com/lucko/spark/issues/119

Thats the reason, we get via RCON a empty string back. And believe me, i tried a lot RCON clients to be sure it's not the Golang lib.

### What could you do?

On thing, I tried out is to use the [overrideTpsCommand](https://spark.lucko.me/docs/Configuration#overridetpscommand) functionality.

When done, as described you will get via tps the "normal" bukkit/papermc output:

```bash
> tps
[19:53:04 INFO]: TPS from last 5s, 1m, 5m, 15m: 20.0, 20.0, 20.0, 20.0
````

This can be picked up from `minecraft-prometheus-exporter`.

Hope this helps, sorry if its not what you may expect.

**Comment by dirien** [comment]
> Console output from `/tps` (is coloured in console):
> 
> ```
> > tps
> [17:16:22 INFO]: TPS from last 5s, 1m, 5m, 15m: 20.0, 20.0, 20.0, 20.0
> ```
> 
> I don't know how I can check this with `RCON` manually.

Hi @TMUniversal,

I fixed the issue with the TPS in PurpurMC and created a new release ->

https://github.com/dirien/minecraft-prometheus-exporter/releases/tag/v0.16.0

**Comment by TMUniversal** [comment]
Working well, thank you!
![image](https://user-images.githubusercontent.com/10200399/183616135-9335b52c-cb88-4b26-abc2-d3cc89e8a3ea.png)
