### ISSUE TITLE
Feature: Include metric that tracks which players are online

### ISSUE THREAD

**Issue by KevBelisle** [dirien/minecraft-prometheus-exporter#83]
List of players online is available through RCON with the "/list" command.

Sample from similar project in Python:

```
        # player
        resp = self.rcon_command("list")
        playerregex = re.compile("players online:(.*)")
        if playerregex.findall(resp):
            for player in playerregex.findall(resp)[0].split(","):
                if not player.isspace():
                    player_online.add_sample('player_online',value=1,labels={'player':player.lstrip()})
```

**Comment by dirien** [comment]
Hi @KevBelisle,

We have this feature already in place:

```go
r := regexp.MustCompile("players online:(.*)")
playersraw := r.FindStringSubmatch(resp)[1]
for _, player := range strings.Fields(strings.ReplaceAll(playersraw, ",", " ")) {
ch <- prometheus.MustNewConstMetric(e.playerOnline, prometheus.CounterValue, 1, strings.TrimSpace(player))
```

The thing is, the metrics appears only when the players are online.

**Comment by KevBelisle** [comment]
Ah, I didn't see it since no one had logged in since I set it up.

Great, works as expected!

**Comment by dirien** [comment]
Hi @KevBelisle, https://github.com/dirien/minecraft-prometheus-exporter/releases/tag/v0.10.0 is up with all the fixes so far! Sorry for the delay, quite busy week start :/

**Comment by KevBelisle** [comment]
These delays are unacceptable. Open source Minecraft projects are of the utmost importance!

I’ll try out the new release later.

**Comment by dirien** [comment]
@KevBelisle, that would be fine! I would add it to the helm chart too! Or you can add it as ConfigMap with the option to set the label (for kube_prometheus_stack)!

Would be dope!
