### ISSUE TITLE
Add Fabric Server Stats

### ISSUE THREAD

**Issue by Mx772** [dirien/minecraft-prometheus-exporter#957]
### Is your feature request related to a problem? Please describe.

n/a

### Describe the solution you'd like

Just as PaperMC/Forge/Etc have a `mod-server-stats` flag. It would be nice for fabric to have one too. 

### Describe alternatives you've considered

n/a

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dirien** [comment]
Fixed with https://github.com/dirien/minecraft-prometheus-exporter/releases/tag/v0.21.0
